### ISSUE TITLE
Age Unlimiter Allows YouTube Ads

### ISSUE THREAD

**Issue by largrizzly** [JustOff/ageless-yt-me#1]
Hello JustOff,

I've found a problem with Age Unlimiter 2.0.2. It allows YouTube ads. I've been trying to figure out why my uBO wasn't blocking YT ads. You can read up about it here: https://forum.palemoon.org/viewtopic.php?f=3&t=26868

Most other people using uBO were having success at blocking the ads on the link provided by Moonchild: https://www.youtube.com/watch?v=5uTjLd6USJo

I was unsuccessful. I created a new profile and installed uBO and viola! The ads were blocked. I found out that if I disabled Age Unlimiter 2.0.2, the problem went away. Re-enabling Age Unlimiter brought back the ads.

Just thought you might have a look into this.

All the Best,
L.A.R. Grizzly

**Comment by largrizzly** [comment]
L.A.R. here again. Maybe you could bring back the toolbar button instead of having Age Unlimiter doing it automatically?

**Comment by JustOff** [comment]
The old method no longer works, but the fix is quite simple and will follow soon.

**Comment by largrizzly** [comment]
Just updated to v 2.0.3 and the problem is resolved. Kudos!

L.A.R.

**Comment by NamesMT** [comment]
Sorry for pinging on this closed issue.

I'm new to Palemoon, suprised on how minimal it runs on a 16GB machine, however one thing been bugging me out:
There's no XUL extension for Audio Only Youtube.
Just asking if you'd be interested in making one.

Thanks!

**Comment by JustOff** [comment]
> Sorry for pinging on this closed issue.

This is a really bad practice, please don't.

> Just asking if you'd be interested in making one.

Given the current state of UXP browsers, I'm not going to start any new XUL extension.
