### ISSUE TITLE
Icon gone

### ISSUE THREAD

**Issue by tingotanca** [JustOff/ageless-yt-me#3]
When installing 2.0.5 on top of 1.0.2, the little green icon in the Toolbar disappears. Problem is, I don't know how to activate the addon in another way. Working from backups of the profile: even if I remove the icon before updating, it disappears from the removed items. (I very seldom come across such videos, which is why I hadn't bothered updating earlier). Thanks for your time,

**Comment by JustOff** [comment]
There is no longer any button in 2.x versions, unlock occurs automatically (if possible).

**Comment by tingotanca** [comment]
Thx.
